# Generated by Django 6.0.5 on 2026-06-12 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0003_favoritefolder_favoritevault"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favoritevault",
            name="user",
        ),
        migrations.RemoveField(
            model_name="favoritevault",
            name="vault",
        ),
        migrations.DeleteModel(
            name="FavoriteFolder",
        ),
        migrations.DeleteModel(
            name="FavoriteVault",
        ),
    ]
